#!/usr/bin/env bash

# shellcheck source=init.sh
source $SCRIPT_DIR/init.sh

checkout_source
# Needs: SOURCE_URI, SOURCE_REF
# Optional: SOURCE_CONTEXT_DIR, BUILD
# Sets: BUILD_DIR

get_version
# Needs: BUILD_DIR
# Optional: NEXT_VERSION, TAG_BRANCHES, PUSH_TAGS
# Sets: NEXT_VERSION, BUILD_NUMBER, PUSH_TAGS, VERSIONABLE, PUSH_JFROG

get_commit_info
# Needs: BUILD_DIR
# Sets: COMMIT_ID, COMMIT_DATE, COMMIT_AUTHOR, COMMIT_MESSAGE

tag_repo
# Needs: BUILD_DIR, NEXT_VERSION
# Optional: PUSH_TAGS, VERSIONABLE

build
# Needs: BUILD_DIR, NEXT_VERSION
# Optional: BUILDER, BUILD_ARGS, DOCKERFILE_CONTEXT_DIR, NODE_VERSION,
# OVERRIDE_DOCKERFILE, POST_BUILD_CMDS, GRADLE_ARGS, NPM_ARGS
# Sets: DOCKERFILE_CONTEXT_DIR

create_docker_image
# Needs: BUILD_DIR, DOCKERFILE_CONTEXT_DIR
# Sets: IMAGE_NAME, NEXT_VERSION_PUSH_URL, PUSH_TAG

push_git_tags
# Needs: BUILD_DIR, NEXT_VERSION
# Optional: PUSH_TAGS, VERSIONABLE

push_to_jfrog
# Needs: NEXT_VERSION_PUSH_URL, IMAGE_NAME, PUSH_TAG, PUSH_JFROG

push_to_openshift
# Needs: OUTPUT_REGISTRY, OPENSHIFT_BUILD_NAMESPACE, IMAGE_NAME, NEXT_VERSION, PUSH_TAG, VERSIONABLE, ACTIVE_TAG

success
